"""empty message

Revision ID: ce633a2962f7
Revises: 9d469f526afe
Create Date: 2020-05-18 18:14:56.774435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ce633a2962f7'
down_revision = '9d469f526afe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('group_invite')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('group_invite',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('public_id_sender', sa.VARCHAR(length=100), nullable=True),
    sa.Column('public_id_invitee', sa.VARCHAR(length=100), nullable=True),
    sa.Column('group_id', sa.INTEGER(), nullable=True),
    sa.Column('token', sa.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id_invitee'),
    sa.UniqueConstraint('public_id_sender'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###
